# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'

inhibit_all_warnings!

target 'AniXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  pod 'SnapKit'
  pod 'MMKV'
  pod 'DanmakuRender-Swift'
  pod 'HandyJSON'
  pod 'VLCKit'
  pod 'Alamofire'
  pod 'DDPCategory', :path => 'LocalPods/DDPCategory'
  pod 'ANXLog', :path => '../Share/ANXLog'
  pod 'ProgressHUD', :path => 'LocalPods/ProgressHUD'
  pod 'FirebaseCrashlytics'
  # Pods for AniXPlayer

end
