# Uncomment the next line to define a global platform for your project
platform :osx, '12.0'

inhibit_all_warnings!

target 'AniXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  pod 'SnapKit'
  pod 'MMKV'
  pod 'DanmakuRender-Swift'
  pod 'VLCKit'
  pod 'Alamofire'
  pod 'DDPCategory', :path => 'LocalPods/DDPCategory'
  pod 'ANXLog', :path => '../Share/ANXLog'
  pod 'ProgressHUD', :path => 'LocalPods/ProgressHUD'
  pod 'FirebaseCrashlytics'
  # pod 'MPVPlayer', :path => 'LocalPods/MPVPlayer'
  # Pods for AniXPlayer

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["MACOSX_DEPLOYMENT_TARGET"] = "12.0"
    end
  end
end