# use_frameworks!

platform :ios, '9.0'

# use_modular_headers!

target 'DDPMediaPlayer_Example' do
  pod 'DDPMediaPlayer', :path => '../../'

  target 'DDPMediaPlayer_Tests' do
    inherit! :search_paths

    
  end
end
