name: dandanplay_path_provider
description: Flutter plugin for getting commonly used locations on the Android &
  iOS file systems, such as the temp and app data directories.
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider
version: 1.6.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.pathprovider
        pluginClass: PathProviderPlugin
      ios:
        pluginClass: FLTPathProviderPlugin
      macos:
        pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.0.0
  meta: ^1.0.5

dev_dependencies:
  e2e: ^0.2.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  uuid: "^1.0.0"
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
