# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

target 'AniXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  pod 'SnapKit'
  pod 'YYCategories'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'NKOColorPickerView'
  pod 'MMKV'
  pod 'DanmakuRender-Swift'
  # pod 'DanmakuRender-Swift', :path => '../../../DanmakuRender-Swift'
  # pod 'HandyJSON', :git => 'https://github.com/Miles-Matheson/HandyJSON.git'
  pod 'MJRefresh'
  pod 'MobileVLCKit'
  # pod 'MobileVLCKit', '3.3.10'
  pod 'Alamofire'
  pod 'AMSMB2'
  pod 'FilesProvider'
  pod "GCDWebServer/WebUploader"
  pod 'DynamicButton'
  pod 'AFNetworking'
  pod 'Ono'
  pod 'ANXLog', :path => '../Share/ANXLog'
  pod 'FirebaseCrashlytics'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
        end
    end
end