# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# flutter_application_path = '../flutter_module'
# load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

inhibit_all_warnings!

target 'AniXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  pod 'SnapKit'
  pod 'YYCategories'
  pod 'MBProgressHUD'
  pod 'YYKeyboardManager'
  # pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'NKOColorPickerView'
  pod 'MMKV'
  pod 'JHDanmakuRender'
  pod 'HandyJSON'
  pod 'MJRefresh'
  pod 'MobileVLCKit', '3.3.10'
  pod 'Alamofire'
  pod 'AMSMB2'
  pod 'FilesProvider'
  pod 'Bugly'
  pod "GCDWebServer/WebUploader"
  pod 'DynamicButton'
  # install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end