# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

inhibit_all_warnings!

target 'AniXPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  
  pod 'NKOColorPickerView'
  pod 'MMKV'
  pod 'MobileVLCKit'
  pod 'AMSMB2'
  pod "GCDWebServer/WebUploader"
  pod 'FirebaseCrashlytics'
  pod 'FSPagerView'
  pod 'JXCategoryView'
  pod 'ANXLog', :path => '../Share/ANXLog'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end