platform :tvos, '17.6'

inhibit_all_warnings!

target 'AniXPlayer' do
  use_frameworks!
  use_modular_headers!

  pod 'ANXLog', :path => '../Share/ANXLog'
  pod 'VLCKit', :path => '../Share/VLCKit'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '17.6'
            end
        end
    end

    system("chmod +x ../scripts/install_hooks.sh && ../scripts/install_hooks.sh")
end
