name: AniXPlayer
options:
  bundleIdPrefix: com.dandanplay
  deploymentTarget:
    tvOS: "13.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    TARGETED_DEVICE_FAMILY: "3"
    INFOPLIST_FILE: AniXPlayer/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
    CODE_SIGN_STYLE: Automatic

packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 7.12.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.9.0
  MMKV:
    url: https://github.com/Tencent/MMKV
    from: 2.0.0
  DanmakuRender-Swift:
    url: https://github.com/sunsx9316/DanmakuRender-Swift
    from: 1.6.0
  ANXLog:
    path: ../Share/ANXLog
  TVVLCKit:
    path: ../Share/TVVLCKit
  GCDWebServer:
    url: https://github.com/sunsx9316/GCDWebServer
    from: 3.6.0

targets:
  AniXPlayer:
    type: application
    platform: tvOS
    sources:
      - path: AniXPlayer
      - path: ../Share/CocoaShare
        excludes:
          - "Objc"
    dependencies:
      - package: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: MMKV
      - package: ANXLog
      - package: GCDWebServer
      - package: GCDWebServer
        product: GCDWebDAVServer
      - package: GCDWebServer
        product: GCDWebUploader
      - package: SnapKit
      - package: Kingfisher
      - package: Alamofire
      - package: DanmakuRender-Swift
        product: DanmakuRender
      - package: TVVLCKit
        product: TVVLCKitSPM
